code/Models/ErrorViewModel.cs
using System;

namespace code.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

code/Models/Movie.cs
using Contentful.Core.Models;
using System;

namespace code.Models
{
    public class Movie
    {
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Actors { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Runtime { get; set; }
        public float IMDBRating { get; set; }
        public string RTRating { get; set; }
        public Asset Poster { get; set; }
    }
}

code/Controllers/FantasyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using code.Models;
using Contentful.Core;

namespace code.Controllers
{
    public class FantasyController : Controller
    {
        private readonly ILogger<FantasyController> _logger;

        private readonly IContentfulClient _client;

        public FantasyController(ILogger<FantasyController> logger, IContentfulClient client)
        {
            _client = client;
            _logger = logger;
        }

        public async Task<IActionResult> Fantasy()
        {
            var movies = await _client.GetEntries<Movie>();
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

code/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using code.Models;
using Contentful.Core;

namespace code.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IContentfulClient _client;

        public HomeController(ILogger<HomeController> logger, IContentfulClient client)
        {
            _client = client;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _client.GetEntries<Movie>();
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

code/Controllers/SciFiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using code.Models;
using Contentful.Core;

namespace code.Controllers
{
    public class SciFiController : Controller
    {
        private readonly ILogger<SciFiController> _logger;

        private readonly IContentfulClient _client;

        public SciFiController(ILogger<SciFiController> logger, IContentfulClient client)
        {
            _client = client;
            _logger = logger;
        }

        public async Task<IActionResult> SciFi()
        {
            var movies = await _client.GetEntries<Movie>();
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

code/Views/Fantasy/Fantasy.cshtml
@{
    ViewData["Title"] = "Fantasy Movies";
}

<h1>Fantasy Movies</h1>

<div id="movieCollection" class="container">
    <div class="row">
        @foreach (var movie in Model)
        {
            if (movie.Genre == "Fantasy")
            {
                <div class="movie col-md-6 col-lg-4">
                    <div class="movieTitle">
                        <img src="@movie.Poster.File.Url" alt="@movie.Poster.Title" width="400" />
                        <h2 class="text-center">@movie.Title</h2>
                    </div>
                    <div class="movieInfo">
                        <p><b>Genre:</b> @movie.Genre</p>
                        <p><b>Director:</b> @movie.Director</p>
                        <p><b>Actors:</b> @movie.Actors</p>
                        <p><b>Release Date:</b> @movie.ReleaseDate.ToString("dd MMMM yyyy")</p>
                        <p><b>Run Time:</b> @movie.Runtime</p>
                        <p><b>IMDB Rating:</b> @movie.IMDBRating/10</p>
                        <p><b>RT Rating:</b> @movie.RTRating</p>
                    </div>
                </div>
            }
        }
    </div>
</div>

code/Views/Home/Index.cshtml
@using Contentful.Core.Models

@model ContentfulCollection<Movie>

@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center">Select a genre</h1>

<div id="selectContainer">
    <ul class="navbar-nav flex-grow-1 text-center">
        <li class="nav-item">
            <a id="scifiSelector" class="genreSelector nav-link" asp-area="" asp-controller="SciFi" asp-action="SciFi">Sci-Fi</a>
        </li>
        <li class="nav-item">
            <a id="fantasySelector" class="genreSelector nav-link" asp-area="" asp-controller="Fantasy" asp-action="Fantasy">Fantasy</a>
        </li>
    </ul>
</div>

code/Views/SciFi/SciFi.cshtml
@{
    ViewData["Title"] = "Sci-Fi Movies";
}

<h1>Sci-Fi Movies</h1>

<div id="movieCollection" class="container">
    <div class="row">
        @foreach (var movie in Model)
        {
            if (movie.Genre == "Sci-Fi")
            {
                <div class="movie col-md-6 col-lg-4">
                    <div class="movieTitle">
                        <img src="@movie.Poster.File.Url" alt="@movie.Poster.Title" width="400" />
                        <h2 class="text-center">@movie.Title</h2>
                    </div>
                    <div class="movieInfo">
                        <p><b>Genre:</b> @movie.Genre</p>
                        <p><b>Director:</b> @movie.Director</p>
                        <p><b>Actors:</b> @movie.Actors</p>
                        <p><b>Release Date:</b> @movie.ReleaseDate.ToString("dd MMMM yyyy")</p>
                        <p><b>Run Time:</b> @movie.Runtime</p>
                        <p><b>IMDB Rating:</b> @movie.IMDBRating/10</p>
                        <p><b>RT Rating:</b> @movie.RTRating</p>
                    </div>
                </div>
            }
        }
    </div>
</div>

code/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom border-dark mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="SciFi" asp-action="SciFi">Sci-Fi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Fantasy" asp-action="Fantasy">Fantasy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 text-light">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top border-dark footer text-muted">
        <div class="container">
            &copy; 2022 - Movies
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>